# Generated by Django 4.0.6 on 2022-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_messagetexttype_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
