# Generated by Django 4.0.6 on 2022-08-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('authentication', '0005_alter_friend_user_one_alter_friend_user_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='chat_messages',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.message'),
            preserve_default=False,
        ),
    ]
