# Generated by Django 4.0.6 on 2022-08-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_friend_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='chat_messages',
            field=models.IntegerField(),
        ),
    ]
