# Generated by Django 4.0.6 on 2022-08-05 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('authentication', '0010_alter_friend_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='chat_messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.message'),
        ),
    ]
